[2025-06-26T09:57:33.507+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-26T09:57:33.550+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_credit_ml_only.training scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-06-26T09:57:33.567+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_credit_ml_only.training scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-06-26T09:57:33.567+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-26T09:57:33.595+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): training> on 2024-09-30 19:00:00+00:00
[2025-06-26T09:57:33.612+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'loan_credit_ml_only', 'training', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/loan_ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp9wunzsbl']
[2025-06-26T09:57:33.617+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask training
[2025-06-26T09:57:33.617+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=245) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-26T09:57:33.618+0000] {standard_task_runner.py:63} INFO - Started process 255 to run task
[2025-06-26T09:57:33.689+0000] {task_command.py:426} INFO - Running <TaskInstance: loan_credit_ml_only.training scheduled__2024-09-30T19:00:00+00:00 [running]> on host 750b8b2e96fa
[2025-06-26T09:57:33.804+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='loan_credit_ml_only' AIRFLOW_CTX_TASK_ID='training' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-06-26T09:57:33.806+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-26T09:57:36.932+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-26T09:57:36.934+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/loan_ml_pipeline_dag.py", line 43, in training_task
    y_tr,      y_te,      y_oot) = modelling.split_data(df_raw, cfg)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/utils/modelling.py", line 56, in split_data
    raise ValueError("OOT window contains 0 rows.")
ValueError: OOT window contains 0 rows.
[2025-06-26T09:57:36.968+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=loan_credit_ml_only, task_id=training, run_id=scheduled__2024-09-30T19:00:00+00:00, execution_date=20240930T190000, start_date=20250626T095733, end_date=20250626T095736
[2025-06-26T09:57:36.985+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task training (OOT window contains 0 rows.; 255)
[2025-06-26T09:57:37.031+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-26T09:57:37.069+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-26T09:57:37.074+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
