[2025-06-26T10:45:59.977+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-26T10:46:00.030+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_credit_ml.training manual__2025-06-26T10:45:28.630036+00:00 [queued]>
[2025-06-26T10:46:00.046+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_credit_ml.training manual__2025-06-26T10:45:28.630036+00:00 [queued]>
[2025-06-26T10:46:00.047+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-26T10:46:00.076+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): training> on 2025-06-26 10:45:28.630036+00:00
[2025-06-26T10:46:00.124+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'loan_credit_ml', 'training', 'manual__2025-06-26T10:45:28.630036+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/loan_ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpmndbmpgp']
[2025-06-26T10:46:00.129+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask training
[2025-06-26T10:46:00.130+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=249) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-26T10:46:00.132+0000] {standard_task_runner.py:63} INFO - Started process 259 to run task
[2025-06-26T10:46:00.211+0000] {task_command.py:426} INFO - Running <TaskInstance: loan_credit_ml.training manual__2025-06-26T10:45:28.630036+00:00 [running]> on host d0c5dbd3b85d
[2025-06-26T10:46:00.361+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='loan_credit_ml' AIRFLOW_CTX_TASK_ID='training' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T10:45:28.630036+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-26T10:45:28.630036+00:00'
[2025-06-26T10:46:00.363+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-26T10:46:07.135+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-26T10:46:07.136+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/loan_ml_pipeline_dag.py", line 52, in training_task
    y_tr,      y_te,      y_oot) = modelling.split_data(df_raw, cfg)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/utils/modelling.py", line 62, in split_data
    raise ValueError("OOT window contains 0 rows.")
ValueError: OOT window contains 0 rows.
[2025-06-26T10:46:07.172+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=loan_credit_ml, task_id=training, run_id=manual__2025-06-26T10:45:28.630036+00:00, execution_date=20250626T104528, start_date=20250626T104600, end_date=20250626T104607
[2025-06-26T10:46:07.194+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 67 for task training (OOT window contains 0 rows.; 259)
[2025-06-26T10:46:07.248+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-26T10:46:07.286+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-26T10:46:07.290+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
