[2025-06-26T10:56:13.214+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-26T10:56:13.292+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_credit_ml.training manual__2025-06-26T10:45:28.630036+00:00 [queued]>
[2025-06-26T10:56:13.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_credit_ml.training manual__2025-06-26T10:45:28.630036+00:00 [queued]>
[2025-06-26T10:56:13.308+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-26T10:56:13.334+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): training> on 2025-06-26 10:45:28.630036+00:00
[2025-06-26T10:56:13.356+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'loan_credit_ml', 'training', 'manual__2025-06-26T10:45:28.630036+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/loan_ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpbnyi6b0u']
[2025-06-26T10:56:13.362+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask training
[2025-06-26T10:56:13.363+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=521) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-26T10:56:13.364+0000] {standard_task_runner.py:63} INFO - Started process 545 to run task
[2025-06-26T10:56:13.467+0000] {task_command.py:426} INFO - Running <TaskInstance: loan_credit_ml.training manual__2025-06-26T10:45:28.630036+00:00 [running]> on host d0c5dbd3b85d
[2025-06-26T10:56:13.609+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='loan_credit_ml' AIRFLOW_CTX_TASK_ID='training' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T10:45:28.630036+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-26T10:45:28.630036+00:00'
[2025-06-26T10:56:13.610+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-26T10:56:26.730+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-26T10:56:26.734+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/loan_ml_pipeline_dag.py", line 52, in training_task
    y_tr,      y_te,      y_oot) = modelling.split_data(df_raw, cfg)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/utils/modelling.py", line 62, in split_data
    raise ValueError("OOT window contains 0 rows.")
ValueError: OOT window contains 0 rows.
[2025-06-26T10:56:26.797+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=loan_credit_ml, task_id=training, run_id=manual__2025-06-26T10:45:28.630036+00:00, execution_date=20250626T104528, start_date=20250626T105613, end_date=20250626T105626
[2025-06-26T10:56:26.836+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 68 for task training (OOT window contains 0 rows.; 545)
[2025-06-26T10:56:26.927+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-26T10:56:26.970+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-26T10:56:26.977+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
