[2025-06-26T10:28:24.772+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-26T10:28:25.726+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_credit_ml.training backfill__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T10:28:25.845+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_credit_ml.training backfill__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T10:28:25.848+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-26T10:28:25.953+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): training> on 2024-10-01 03:00:00+00:00
[2025-06-26T10:28:26.000+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'loan_credit_ml', 'training', 'backfill__2024-10-01T03:00:00+00:00', '--job-id', '64', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/loan_ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp38o5ebzl']
[2025-06-26T10:28:26.005+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask training
[2025-06-26T10:28:26.011+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=682) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-26T10:28:26.014+0000] {standard_task_runner.py:63} INFO - Started process 683 to run task
[2025-06-26T10:28:26.473+0000] {task_command.py:426} INFO - Running <TaskInstance: loan_credit_ml.training backfill__2024-10-01T03:00:00+00:00 [running]> on host c3b6b758a64d
[2025-06-26T10:28:27.471+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='loan_credit_ml' AIRFLOW_CTX_TASK_ID='training' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-10-01T03:00:00+00:00'
[2025-06-26T10:28:27.479+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-26T10:28:41.711+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-26T10:28:41.713+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/loan_ml_pipeline_dag.py", line 52, in training_task
    y_tr,      y_te,      y_oot) = modelling.split_data(df_raw, cfg)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/utils/modelling.py", line 56, in split_data
    raise ValueError("OOT window contains 0 rows.")
ValueError: OOT window contains 0 rows.
[2025-06-26T10:28:41.751+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=loan_credit_ml, task_id=training, run_id=backfill__2024-10-01T03:00:00+00:00, execution_date=20241001T030000, start_date=20250626T102825, end_date=20250626T102841
[2025-06-26T10:28:41.774+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task training (OOT window contains 0 rows.; 683)
[2025-06-26T10:28:41.842+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-26T10:28:41.895+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-26T10:28:41.904+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
